# Filtragem Inicial de Dados

In [1]:
# Importação de bibliotecas
import pandas as pd
import numpy as np

In [2]:
# Importando o arquivo .CSV
caminho = 'C:/Users/raphael.eugenio/Desktop/Raphael/'
dados_iniciais = 'paises.csv'

df = pd.read_csv(dados_iniciais)

print(df.head())

     id           pais codigo confederacao  ranking
0  4734         México    MEX     CONCACAF       15
1  4740  África do Sul    RSA          CAF       59
2  4400  Coreia do Sul    KOR          AFC       22
3  4705       Tchéquia    CZE         UEFA       40
4  4724         Canadá    CAN     CONCACAF       40

In [3]:
df.columns

Index(['id', 'pais', 'codigo', 'confederacao', 'ranking'], dtype='str')

*CONCACAF - América do Norte e Central*

# Filtrando paises por continente

In [10]:
concacaf = df.loc[df['confederacao'] == 'CONCACAF']
# df_concacaf = df[concacaf]
concacaf

      id     pais codigo confederacao  ranking
0   4734   México    MEX     CONCACAF       15
4   4724   Canadá    CAN     CONCACAF       40
10  4722    Haiti    HAI     CONCACAF       90
12  4725      EUA    USA     CONCACAF       13
17  4720  Curaçao    CUW     CONCACAF       91
47  4717   Panamá    PAN     CONCACAF       43

*CONMEBOL - América do Sul*

In [11]:
conmebol = df.loc[df['confederacao'] == 'CONMEBOL']
conmebol

      id       pais codigo confederacao  ranking
8   4425     Brasil    BRA     CONMEBOL        5
13  4823   Paraguai    PAR     CONMEBOL       56
19  4819    Equador    ECU     CONMEBOL       31
31  4422    Uruguai    URU     CONMEBOL       11
36  4481  Argentina    ARG     CONMEBOL        1
41  4820   Colômbia    COL     CONMEBOL       12

*UEFA - Europa*

In [9]:
uefa = df.loc[df['confederacao'] == 'UEFA']
uefa

      id                  pais codigo confederacao  ranking
3   4705              Tchéquia    CZE         UEFA       40
5   4697  Bósnia e Herzegovina    BIH         UEFA       74
7   4489                 Suíça    SUI         UEFA       19
11  4486               Escócia    SCO         UEFA       39
15  4703               Turquia    TUR         UEFA       35
16  4482              Alemanha    GER         UEFA       16
20  4492               Holanda    NED         UEFA        7
22  4491                Suécia    SWE         UEFA       28
24  4485               Bélgica    BEL         UEFA        8
28  4493               Espanha    ESP         UEFA        3
32  4480                França    FRA         UEFA        2
35  4488               Noruega    NOR         UEFA       47
38  4711               Áustria    AUT         UEFA       25
40  4483              Portugal    POR         UEFA        6
44  4438            Inglaterra    ENG         UEFA        4
45  4494               Croácia    CRO         UEFA       10

*AFC - Ásia*

In [8]:
afc = df.loc[df['confederacao'] == 'AFC']
afc

      id            pais codigo confederacao  ranking
2   4400   Coreia do Sul    KOR          AFC       22
6   4406           Catar    QAT          AFC       37
14  4408       Austrália    AUS          AFC       24
21  4412           Japão    JPN          AFC       18
26  4407             Irã    IRN          AFC       20
30  4411  Arábia Saudita    KSA          AFC       53
34  4405          Iraque    IRQ          AFC       58
39  4409        Jordânia    JOR          AFC       71
42  4413     Uzbequistão    UZB          AFC       64

*CAF - África*

In [12]:
caf = df.loc[df['confederacao'] == 'CAF']
caf

      id             pais codigo confederacao  ranking
1   4740    África do Sul    RSA          CAF       59
9   4741         Marrocos    MAR          CAF       13
18  4745  Costa do Marfim    CIV          CAF       38
23  4755          Tunísia    TUN          CAF       41
25  4744            Egito    EGY          CAF       36
29  4742       Cabo Verde    CPV          CAF       65
33  4754          Senegal    SEN          CAF       17
37  4691          Argélia    ALG          CAF       43
43  4746         RD Congo    COD          CAF       63
46  4747             Gana    GHA          CAF       68

*OFC - Oceania*

In [7]:
ofc = df.loc[df['confederacao'] == 'OFC']
print(ofc.head())

      id           pais codigo confederacao  ranking
27  4424  Nova Zelândia    NZL          OFC      103

# Classificações (Ranking FIFA)

In [ ]:
df